# -*- coding: utf-8 -*-
"""
/***************************************************************************
 usosCatastro
                                 A QGIS plugin
 Parcelas catastrales con usos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-22
        copyright            : (C) 2021 by UAH
        email                : juanmamap@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load usosCatastro class from file usosCatastro.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .usos_catastro import usosCatastro
    return usosCatastro(iface)
